class Animation {
    contructor() {}
    
    /**
     * Creates a grid from an Image
     * @function newGrid
     * @param { Number } frameWidth  Frame Width
     * @param { Number } frameHeight  Frame Height
     * @param { Number } imageHeight  Image Width
     * @param { Number } imageHeight  Image Height
     * @return { Object }             Return a grid object with the x and y coordinates of the frames within the image
     */
    newGrid(frameWidth, frameHeight, imageWidth, imageHeight, sx, sy) {
        const grid = {}
        let frames = {}

        for (let i = 0; i < imageHeight / frameHeight; i++) {
            for (let j = 0; j < imageWidth / frameWidth; j++) {
                frames[j] = { x: sx + j * frameWidth, y: sy + i * frameHeight };
            }
            grid[i] = frames
            frames = {}
        }
        // console.log(grid);

        return function (frames, line) {
            let nGrid = grid;
            let min = frames.split("-")[0]
            let max = frames.split("-")[1];
            let respGrid = {
                frameWidth: frameWidth,
                frameHeight: frameHeight,
                line: parseInt(line),
                min: parseInt(min),
                max: parseInt(max),
                frames: {}
            }

            for (let [key, value] of Object.entries(nGrid[line.toString()])) {
                if (parseInt(key) >= parseInt(min) && parseInt(key) <= parseInt(max)) {
                    respGrid.frames[key] = value;
                }
            }
            // console.log(JSON.stringify(respGrid));
            return respGrid;
        }
    }

    /**
     * Create a new animation
     * @function newAnimation
     * @param  { Object } frames    Receives a grid object generated by the newGrid function
     * @param { number } fps        Animation fps
     * @param { Bool } loop         animation loop, true or false
     * @return { Object }           Returns an object with update and draw methods
     */
    newAnimation(frames, fps, loop) {
        return Object.create({
            line: frames.line,
            min: frames.min,
            max: frames.max,
            frameWidth: frames.frameWidth,
            frameHeight: frames.frameHeight,
            frames: frames.frames,
            fps: fps,
            loop: loop,
            countTime: 0,
            currentFrame: frames.min,
            animationFinished: false,
            /**
             * Update animation
             * @function upadate
             * @param { Number } dt    Delta time
             */
            update: function (dt) {
                this.countTime += dt;
                if (this.countTime >= 1 / this.fps) {
                    this.countTime = 0;
                    this.currentFrame++;
                    if (this.currentFrame > this.max) {
                        if (this.loop) {
                            this.currentFrame = this.min;
                            this.animationFinished = false;
                        }
                        else {
                            this.animationFinished = true;
                            this.currentFrame = this.max;
                        };
                    }
                }
                
            },
            /**
             * Draw animation
             * @function draw
             * @param { Object } ctx    Canvas context
             * @param { Object } image  Image to be drawn
             * @param { Number } x      X position
             * @param { Number } y      Y position
             */
            draw: function (ctx, image, x, y, hFlip = 1, vFlip = 1) {
                ctx.save();
                ctx.scale(hFlip, vFlip);
                ctx.drawImage(
                    image,
                    this.frames[(this.currentFrame).toString()].x,
                    this.frames[(this.currentFrame).toString()].y,
                    this.frameWidth,
                    this.frameHeight,
                    x,
                    y,
                    this.frameWidth,
                    this.frameHeight
                );
                ctx.restore();
            },
            /**
             * Check if animation is finished
             * @function isFineshed
             */
            isFinished: function () {
                if (this.animationFinished) {
                    this.animationFinished = false;
                    this.currentFrame = this.min;
                    return true;
                }

                return false;
            }
        });
    }

}


export { Animation };

